name: principle_utils
description: "Principle Utils: A Dart package for Flutter with responsive layouts, string case conversions, color utilities, and type-safe patterns. Simplify development with intuitive extensions and consistent theming."

version: 0.1.4

homepage: https://github.com/PrincipleConsulting/principle_utils
repository: https://github.com/PrincipleConsulting/principle_utils

environment:
  sdk: ^3.5.4
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4