name: principle_utils
description: "Principle Flutter Utils Package"
version: 0.1.0
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter: