# .github/workflows/publish.yml
name: Publish to pub.dev

on:
  pull_request:
    branches: 
      - main
    types: [closed]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'  # Must match your pub.dev tag pattern (e.g., v1.2.3)

jobs:
  publish:
    permissions:
      id-token: write  # Required for OIDC authentication with pub.dev
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the repository code.
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history for version/tag info.

      # 2. Set up Dart (using the official Dart action).
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      # 3. Get package dependencies.
      - name: Install dependencies
        run: dart pub get

      # 4. (Optional) Run tests or generate code if needed.
      - name: Run tests
        run: dart test

      # 5. Publish the package to pub.dev.
      # Ensure that your pub credentials (a JSON file) are stored in the secret `PUB_CREDENTIALS`.
      - name: Publish package
        env:
          PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
        run: dart pub publish --skip-confirmation
