# .github/workflows/publish.yml
name: Publish to pub.dev


on:
  pull_request:
    types: [closed]

jobs:
  publish:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'release'
    permissions:
      id-token: write  # Required for OIDC authentication with pub.dev    
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      # Specify the github actions deployment environment
      environment: pub.dev
